sudo: required
services:
  - docker

before_install:
  - docker build -t hrudyusa/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run hrudyusa/react-test npm test -- --coverage

after_success:
  - docker build -t hrudyusa/multi-client -f ./client 
  - docker build -t hrudyusa/multi-nginx -f ./nginx 
  - docker build -t hrudyusa/multi-server -f ./server 
  - docker build -t hrudyusa/multi-worker -f ./worker 
# Log into docker CLI 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push hrudyusa/multi-client
  - docker push hrudyusa/multi-nginx
  - docker push hrudyusa/multi-server
  - docker push hrudyusa/multi-worker
# take images and pushd them to docker-hub
#deploy:
#  provider: elasticbeanstalk
#  region: "us-east-1"
#  app: "docker-react"
#  env: "DockerReact-env"
#  bucket_name: "elasticbeanstalk-us-east-1-207076753345"
#  bucket_path: "docker-react"
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key:
#    secure: "$AWS_SECRET_KEY"
